### ISSUE TITLE
WP3 Focusing: Check with W3C how to properly annotate html with references to standard terminologies

### ISSUE THREAD

**Issue by Paride07** [Gravitate-Health/MVP2#116]

**Comment by Paride07** [comment]
@abelmarm and @amedranogil is this task closed?
Please add within this card following information:
- add issue description
- add issue update

**Comment by amedranogil** [comment]
yes the task is closed.
The result was the proposal of RDFa for anotation. Now it needs to go through HL7 standarization (WP5)

**Comment by Paride07** [comment]
@amedranogil ok thanks I will move to Column done
